File Hash Generator
Panelinha-Inc/resume-ai-api pull request #1
Opened 2021-04-24 19:46 UTC by JedersonLuz

# File Hash Generator

Esta branch tinha por objetivo padronizar o nome dos arquivos recebidos pela API utilizando hash. Para isso foi utilizado uma função built-in do Python para gerar um hash md5, função esta que é muito conhecida por ser utilizado na verificação de integridade de arquivos transferidos via rede.

As modificações realizadas neste PR seguem descritas abaixo:

* O módulo gerador de hash de arquivo foi completamente desenvolvido, testado e adicionado ao projeto; e
* A API foi atualizada para utilizar o novo módulo para nomear os arquivos recebidos com seu hash.

2021-04-25 01:30 UTC, VitoriaCarvalho requested changes

2021-04-25 01:30 UTC, VitoriaCarvalho commented on api.py
> +  with open(f'./uploaded_files/{new_filename}.pdf', 'wb') as f:
Como a aplicação permitirá o upload de imagens, acredito que será necessário modificar essa linha de código.

2021-04-25 01:33 UTC, JedersonLuz commented on api.py
> +  with open(f'./uploaded_files/{new_filename}.pdf', 'wb') as f:
Hum, é verdade.

Quando fiz esse código acabei me esquecendo desse detalhe e considerei apenas arquivos PDF.

Mas tendo isso em vista irei realizar uma modificação para verificar o formato efetivo do arquivo para salvá-lo de maneira adequada. 😊✨

2021-04-25 01:39 UTC, VitoriaCarvalho commented on api.py
> +  with open(f'./uploaded_files/{new_filename}.pdf', 'wb') as f:
Good Job :)

2021-04-26 19:16 UTC, Gas-Helio approved these changes
👌

2021-04-26 19:36 UTC, JedersonLuz commented on api.py
> +  with open(f'./uploaded_files/{new_filename}.pdf', 'wb') as f:
Adicionei a modificação solicitada. ^^

Agora a API é capaz de salvar arquivos de outros formatos. Inclusive já testei os formatos jpg e png para garantir o bom funcionamento da rota.

2021-04-27 00:47 UTC, acucenarodrigues1998 approved these changes

2021-04-27 01:17 UTC, VitoriaCarvalho commented on api.py
> +  with open(f'./uploaded_files/{new_filename}.pdf', 'wb') as f:
GG!

2021-04-27 01:18 UTC, VitoriaCarvalho approved these changes

2021-04-27 01:22 UTC, merged